# Generated by Django 3.0.6 on 2020-05-08 16:54

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200508_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[accounts.validators.DNIValidator()], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[accounts.validators.PhoneValidator()]),
        ),
    ]
