# Generated by Django 3.0.6 on 2020-05-08 17:15

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200508_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[accounts.validators.NameValidator()], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[accounts.validators.NameValidator()], verbose_name='Apellidos'),
        ),
    ]
