# Generated by Django 3.0.6 on 2020-05-22 00:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import financing.models
import financing.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('code', models.UUIDField(default=financing.models.generate_code_guarantee, editable=False, primary_key=True, serialize=False, verbose_name='Código')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))], verbose_name='Valor')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
            ],
        ),
        migrations.CreateModel(
            name='GuaranteeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de garantía')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('application_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de término')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))], verbose_name='Monto')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto')),
                ('code', models.UUIDField(default=financing.models.generate_code_loan, editable=False, primary_key=True, serialize=False, verbose_name='Código')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_client', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('guarantee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financing.Guarantee', verbose_name='Garantia')),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_guarantor', to=settings.AUTH_USER_MODEL, verbose_name='Fiador')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('application_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de término')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))], verbose_name='Monto')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto')),
                ('code', models.UUIDField(default=financing.models.generate_code_investment, editable=False, primary_key=True, serialize=False, verbose_name='Código')),
                ('bank_account', models.CharField(max_length=30, validators=[financing.validators.BankAccountValidator()], verbose_name='Numero de cuenta')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_client', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Inversión',
                'verbose_name_plural': 'Inversiónes',
            },
        ),
        migrations.AddField(
            model_name='guarantee',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financing.GuaranteeType', verbose_name='Tipo'),
        ),
    ]
