# Generated by Django 3.0.6 on 2020-05-22 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de término'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de término'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
    ]
