# Generated by Django 3.0.6 on 2020-06-21 20:26

from django.db import migrations, models
import django.db.models.deletion
import financing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0003_auto_20200608_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('planned_date', models.DateField(verbose_name='Fecha planificada')),
                ('effective_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha efectiva')),
                ('method', models.PositiveSmallIntegerField(choices=[(0, 'Pago en efectivo'), (1, 'Depósito bancario'), (2, 'Cheque'), (3, 'Transferencia directa')], verbose_name='Método de pago')),
                ('voucher', models.CharField(max_length=100, validators=[financing.validators.VoucherValidator()], verbose_name='Comprobante')),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment', to='financing.Loan', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Pago de préstamo',
                'verbose_name_plural': 'Pagos de préstamo',
            },
        ),
        migrations.CreateModel(
            name='InvestmentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('planned_date', models.DateField(verbose_name='Fecha planificada')),
                ('effective_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha efectiva')),
                ('method', models.PositiveSmallIntegerField(choices=[(0, 'Pago en efectivo'), (1, 'Depósito bancario'), (2, 'Cheque'), (3, 'Transferencia directa')], verbose_name='Método de pago')),
                ('voucher', models.CharField(max_length=100, validators=[financing.validators.VoucherValidator()], verbose_name='Comprobante')),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_payment', to='financing.Investment', verbose_name='Inversión')),
            ],
            options={
                'verbose_name': 'Pago de inversión',
                'verbose_name_plural': 'Pagos de inversión',
            },
        ),
    ]
