# Generated by Django 3.0.6 on 2020-07-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0005_auto_20200621_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='loan',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nombre'),
        ),
    ]
