# Generated by Django 3.0.6 on 2020-05-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_authorize',
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve',
            field=models.BooleanField(default=False, verbose_name='Puede aprobar'),
        ),
    ]
